### ISSUE TITLE
SpriteManager does not work on Arduino Due

### ISSUE THREAD

**Issue by jdimauro** [jdimauro/witch-lights#3]
When I try to run the SpriteManager code on the Arduino Due powering the witch lights, I get no animation. Possible that there's just a missing line in the code (see the top of the `witch-lights-classic.ino` file).

**Comment by tenner** [comment]
Resolved at the April 2 hackathon. `SpriteManager` seems to be behaving pretty well on a 750-LED configuration. I still think there are some performance improvements that can be made.
