### ISSUE TITLE
Cannot compile more_sprites due to missing libraries

### ISSUE THREAD

**Issue by jdimauro** [jdimauro/witch-lights#6]
The `witch_lights_more_sprites.ino` file calls several un-included libraries. 

We need to either include those libraries or provide download links in a README.

**Comment by tenner** [comment]
I should create a lib/ directory and include the files there. Need to figure out the Arduino-ish way to do this for a public software project. Will resolve soon; in the meantime feel free to google the offending library and put import it into the Arduino ide.

**Comment by tenner** [comment]
Ok, it's still broken, but I'm slowly learning how to do this properly. I think the best way (maybe) is to provide a "lib" directory in which these can be stored so all *.ino files in the project can reference them. However, it appears to be a limitation of the Arduino environment to not be able to search out of a project's own folder for additional files. Symlinks appear to work, though, so my goal is to create a symlink in each folder which references the master library. Symlinks appear to work fine in git, as well, so there shouldn't be version control implications of this.

Yes, I realize the simple thing to do would just be to link to the library and provide documentation, but that doesn't seem like the "right" answer.

**Comment by tenner** [comment]
Added libraries to arduino/lib. This DOES require human intervention; developers need to install the libraries manually in their Arduino IDEs. However, this is now compiling for me as is with a fresh clone so hopefully it should do the same for others^H^H^H^H^H^Hyou, Josh.
